---
- name: Add apt repo for java
  apt_repository: repo='ppa:webupd8team/java'
  sudo: true

- name: Update packages
  apt: upgrade=dist update_cache=yes
  sudo: true

- name: Auto accept java license
  sudo: true
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Install libraries and apps
  apt: name={{item}} state=latest
  sudo: true
  with_items:
    - curl
    - git
    - wget
    - htop
    - vim
    - zsh
    - oracle-java8-installer
    - virtualbox
    - python-pip

- name: Change shell to ZSH
  sudo: true
  user: shell=/bin/zsh name={{ansible_ssh_user}}
