---
- name: Add apt repo for java
  apt_repository: repo='ppa:webupd8team/java'
  sudo: true

- name: Add apt repo for google chrome
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present
  sudo: true

- name: Update packages
  apt: upgrade=dist update_cache=yes
  sudo: true

- name: Auto accept java license
  sudo: true
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Install libraries and apps
  apt: name={{item}} state=latest
  sudo: true
  with_items:
    - curl
    - git
    - wget
    - htop
    - vim
    - zsh
    - build-essential
    - oracle-java8-installer
    - virtualbox
    - python-pip
    - jmeter
    - tmux
    - libxml2-utils
    - xsltproc
    - indicator-multiload
    - meld
    - google-chrome-stable
    - ubuntu-mate-core
    - ubuntu-mate-desktop

- name: Download Vagrant deb files
  get_url: 
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
    dest=/tmp/vagrant.deb

- name: Install deb files
  sudo: true
  apt: deb=/tmp/vagrant.deb

- name: Download Atom deb files
  get_url: 
    url=https://atom.io/download/deb
    dest=/tmp/atom.deb
                
- name: Install deb files
  sudo: true
  apt: deb=/tmp/atom.deb

- name: Setup Node install
  sudo: true
  shell: curl -sL https://deb.nodesource.com/setup_4.x | bash -

- name: Install Node
  sudo: true
  apt: name=nodejs state=latest

- name: Update keyboard layout
  sudo: true
  shell: sed -i 's/XKBLAYOUT.*/XKBLAYOUT="uk"/g' /etc/default/keyboard

- name: Update keyboard model
  sudo: true
  shell: sed -i 's/XKBMODEL.*/XKBMODEL="pc105"/g' /etc/default/keyboard

- name: Change shell to ZSH
  sudo: true
  user: shell=/bin/zsh name={{ansible_ssh_user}}

