---
  
- name: Setup Node install
  sudo: true
  shell: curl -sL https://deb.nodesource.com/setup_4.x | bash -

- name: Install Node
  sudo: true
  apt: name=nodejs state=latest

- name: Install globals
  sudo: true
  npm: name={{item}} global=yes
  with_items:
    - browserify
    - webpack
    - jspm
    - bower
